added env. for remoteConfig
syngenta-digital/package-node-planting-common-ops pull request #11
Opened 2024-03-07 12:56 UTC by himanshu-2764

2024-03-07 13:00 UTC, RambhauWaykar requested changes

2024-03-07 13:00 UTC, RambhauWaykar commented on src/modules/env/.env.dev
> +remoteConfig__baseUrl=https://cropwise-api-node-css-config-dev.azurewebsites.net
change url to https://cropwise-api-node-css-config-staging.azurewebsites.net

2024-03-07 13:00 UTC, RambhauWaykar commented on src/modules/env/.env.qa
> +remoteConfig__environment=uat
change environment to qa

2024-03-07 13:00 UTC, RambhauWaykar commented on src/modules/env/.env.staging
> +remoteConfig__environment=staging
change environment to uat

2024-03-07 13:00 UTC, vansham69420 commented on src/modules/env/.env.uat
> +remoteConfig__baseUrl=https://cropwise-api-node-css-config-staging.azurewebsites.net
remoteConfig=`{}`

2024-03-07 13:10 UTC, RambhauWaykar approved these changes

2024-03-08 04:45 UTC, vansham69420 approved these changes

2024-03-08 04:51 UTC, prashantSyngenta approved these changes

2024-03-08 04:52 UTC, merged