CWPT-746 | improvement: Some improvements in the package
syngenta-digital/package-node-planting-common-ops pull request #9
Opened 2024-02-27 07:29 UTC by vansham69420

- Implemented Prettier
- More linting rules
- Included the .env files in the dist folder.
- Removed src folder during build and packaging
- Error handling in the `generateName` function

2024-02-27 11:20 UTC, prashantSyngenta approved these changes

2024-02-27 11:26 UTC, himanshu-2764 approved these changes

2024-02-28 02:45 UTC, RambhauWaykar requested changes

2024-02-28 02:45 UTC, RambhauWaykar commented on src/modules/env/.env.production
> +# CROPWISE PLANTING DEV CONFIGURATION FOR PROD ENVIRONMENT
why 2 env files for production?

2024-02-28 02:45 UTC, RambhauWaykar commented on src/modules/env/.env.production
> +    "password":"0HOetynAQ7zG"
why this password here? can we store it in secret manager?

2024-02-28 04:17 UTC, vansham69420 commented on src/modules/env/.env.production
> +# CROPWISE PLANTING DEV CONFIGURATION FOR PROD ENVIRONMENT
azure uses the env name `production` while in AWS we are going ahead with `prod`. Hence to support the dual deployment to Azure and AWS. Also this is a temporary measure. Once migration to AWS is done, `production` and `staging` files are null and void.

2024-02-28 04:17 UTC, vansham69420 commented on src/modules/env/.env.production
> +    "password":"0HOetynAQ7zG"
Sure

2024-02-28 05:04 UTC, RambhauWaykar approved these changes

2024-02-28 07:54 UTC, merged